/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.awt.image.BufferedImage;
import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException, ArrayIndexOutOfBoundsException {

        String input = args[0];
        String output = args[1];
        String method = args[2];
        BufferedImage img;

        if (method.contains("white")) method = "white-[newColor]";

        switch (method) {
            case "white-[newColor]":
                int dash = args[2].indexOf('-');
                String newColor = args[2].substring(dash + 1);
                img = BitMap.swapWhiteWithNewColor(input, newColor);
                BitMap.saveBufferedImageAsBMP(img, output);
                break;
            case "rotate":
                img = BitMap.rotate(input);
                BitMap.saveBufferedImageAsBMP(img, output);
                break;
            case "mirror":
                img = BitMap.mirror(input);
                BitMap.saveBufferedImageAsBMP(img, output);
                break;
            default:
                System.out.println("The transform you provided is not supported.");
        }
    }
}
